import React, { createContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation data
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    login: "Login",
    logout: "Logout",
    register: "Register",
    dashboard: "Dashboard",
    transactions: "Transactions",
    settings: "Settings",
    profile: "Profile",
    marketplace: "Marketplace",
    products: "Products",
    search: "Search",
    filters: "Filters",
    verified: "Verified",
    reviews: "Reviews",
    vendors: "Vendors",
    about: "About",
    features: "Features",
    // Dashboard
    total_revenue: "Total Revenue",
    total_commissions: "Total Commissions",
    total_transactions: "Total Transactions",
    success_rate: "Success Rate",
    recent_transactions: "Recent Transactions",
    // Payment
    mobile_money: "Mobile Money",
    card_payment: "Card Payment",
    payment_success: "Payment Successful",
    payment_failed: "Payment Failed",
    // Onboarding
    business_info: "Business Information",
    owner_info: "Owner Information",
    kyc_documents: "KYC Documents",
    bank_details: "Bank Details",
    review_submit: "Review & Submit",
    // Forms
    email: "Email",
    password: "Password",
    first_name: "First Name",
    last_name: "Last Name",
    phone: "Phone Number",
    submit: "Submit",
    cancel: "Cancel",
    continue: "Continue",
    back: "Back",
    // Landing Page
    hero_title: "Your Online Business, Simplified.",
    hero_subtitle: "Create your shop, manage orders, and track revenue in real-time. An intuitive platform for ambitious vendors and discerning buyers.",
    start_selling: "Start Selling Today",
    browse_marketplace: "Browse Marketplace",
    get_started: "Get Started",
    become_vendor: "Become a Vendor",
    stat_vendors: "Active Vendors",
    stat_transactions: "Transactions",
    stat_satisfaction: "Satisfaction Rate",
    stat_support: "Customer Support",
    features_title: "Everything You Need to Succeed",
    features_subtitle: "Powerful features designed for African merchants and shoppers",
    feature_marketplace: "Vendor Dashboard",
    feature_marketplace_desc: "Track performance, sales, and products with an interactive dashboard.",
    feature_payments: "Order Management",
    feature_payments_desc: "Manage orders from receipt to delivery with real-time status updates.",
    feature_secure: "Secure & Compliant",
    feature_secure_desc: "Integrated KYC process to ensure verified vendors and secure transactions.",
    feature_analytics: "Real-time Analytics",
    feature_analytics_desc: "Track sales, revenue, and customer insights in real-time",
    feature_multilang: "Multi-language Support",
    feature_multilang_desc: "Serve customers in English and French",
    feature_fast: "Fast & Reliable",
    feature_fast_desc: "Lightning-fast platform with 99.9% uptime guarantee",
    how_it_works: "How It Works",
    how_it_works_subtitle: "Get started in three simple steps",
    step_register: "Sign Up & Verify",
    step_register_desc: "Create your account and complete the KYC process to become a verified vendor",
    step_setup: "Stock Your Shop",
    step_setup_desc: "Add products, manage inventory, and set prices easily",
    step_sell: "Sell & Earn",
    step_sell_desc: "Receive orders, manage shipments, and track your earnings",
    benefits_title: "Why Choose FinMarket",
    benefits_subtitle: "Join thousands of successful merchants",
    benefit_commission: "Transparent commission rates",
    benefit_dashboard: "Real-time analytics dashboard",
    benefit_mobile: "Mobile-first design - manage your shop on the go",
    benefit_support: "24/7 customer support in multiple languages",
    benefit_kyc: "Fast KYC verification",
    benefit_international: "Accept international payments",
    cta_title: "Ready to Start Selling?",
    cta_subtitle: "Join our marketplace today and grow your business",
    create_account: "Create Your Account",
    footer_desc: "Africa's leading fintech marketplace platform",
    footer_product: "Product",
    footer_company: "Company",
    footer_legal: "Legal",
    pricing: "Pricing",
    about_us: "About Us",
    contact: "Contact",
    careers: "Careers",
    privacy_policy: "Privacy Policy",
    terms_service: "Terms of Service",
    cookies: "Cookies",
    all_rights_reserved: "All rights reserved",
    // About Page
    about_title: "About FinMarket",
    about_subtitle: "Empowering African commerce through technology",
    about_content: "FinMarket is a leading digital marketplace platform designed to connect merchants and customers across Africa. Our mission is to provide equal economic opportunity by building a reliable, secure, and easy-to-use platform for buying and selling goods and services.",
    // Contact Page
    contact_title: "Contact Us",
    contact_subtitle: "We're here to help",
    contact_address: "123 Business District, Cotonou, Benin",
    contact_email: "support@finmarket.com",
    contact_phone: "+229 01 23 45 67",
    send_message_btn: "Send Message",
    message_sent: "Message sent! We'll get back to you soon.",
    // Privacy & Terms
    privacy_title: "Privacy Policy",
    privacy_intro: "At FinMarket, we take your privacy seriously. This policy describes how we collect and use your data.",
    terms_title: "Terms of Service",
    terms_intro: "By using FinMarket, you agree to these terms. Please read them carefully.",
    last_updated: "Last updated: February 2026",
    privacy_section1_title: "1. Data Collection",
    privacy_section1_text: "We collect information you provide directly to us, such as when you create or modify your account, request on-demand services, contact customer support, or otherwise communicate with us.",
    privacy_section2_title: "2. Usage of Information",
    privacy_section2_text: "We use the information we collect to provide, maintain, and improve our services, such as to facilitate payments, send receipts, provide products and services you request (and send related information), develop new features, provide customer support to Users and Vendors.",
    privacy_section3_title: "3. Data Security",
    privacy_section3_text: "We implement appropriate technical and organizational measures to help protect your personal data from unauthorized access, use, disclosure, alteration, or destruction.",
    terms_section1_title: "1. Acceptance of Terms",
    terms_section1_text: "By accessing or using our services, you agree to be bound by these terms. If you do not agree to these terms, you may not access or use the services.",
    terms_section2_title: "2. Vendor Obligations",
    terms_section2_text: "Vendors must provide accurate information about their products and services. Vendors are responsible for fulfilling orders and ensuring customer satisfaction.",
    terms_section3_title: "3. User Obligations",
    terms_section3_text: "Users verify that they are at least 18 years of age. Users are responsible for maintaining the confidentiality of their account credentials.",
    terms_section4_title: "4. Payments",
    terms_section4_text: "All payments are processed securely. FinMarket is not responsible for any issues arising from third-party payment processors.",
    message_label: "Message",

    about_section2_content: "We believe in the power of technology to transform lives. By connecting sellers with buyers, we create value for everyone in the ecosystem. Our platform is built on trust, transparency, and efficiency.",
    // Marketplace
    marketplace_title: "Discover Amazing Vendors",
    marketplace_subtitle: "Browse through hundreds of verified vendors and find exactly what you need",
    // Admin Orders
    orders_management: "Orders Management",
    manage_all_orders: "Manage all orders",
    total_revenue: "Total Revenue",
    platform_commission: "Platform Commission",
    commission_rate: "Commission Rate",
    all_vendors: "All Vendors",
    vendor: "Vendor",
    search_orders: "Search orders",
    // Admin Drivers
    drivers_management: "Drivers Management",
    manage_drivers_subtitle: "List of partner drivers and direct contact",
    drivers_list: "Drivers List",
    search_driver: "Search driver...",
    driver_name: "Name",
    zone: "Zone",
    orders_completed: "Completed Orders",
    add_driver: "Add Driver",
    edit_driver: "Edit Driver",
    delete_driver: "Delete Driver",
    delete_driver_confirm: "Are you sure you want to delete this driver? This action cannot be undone.",
    driver_added: "Driver added successfully",
    driver_updated: "Driver updated successfully",
    driver_deleted: "Driver deleted successfully",
    no_drivers_found: "No drivers found",
    available: "Available",
    busy: "Busy",
    offline: "Offline",
    name: "Name",
    save: "Save",
    filters: "Filters",
    start_date: "Start Date",
    end_date: "End Date",
    status: "Status",
    all_statuses: "All Statuses",
    clear: "Clear",
    orders: "Orders",
    newest_first: "Newest first",
    oldest_first: "Oldest first",
    no_orders_found: "No orders found",
    order_number: "Order Number",
    date: "Date",
    customer: "Customer",
    amount: "Amount",
    actions: "Actions",
    confirm_delete: "Confirm Delete",
    delete_order_warning: "Are you sure you want to delete this order? This action cannot be undone.",
    delete: "Delete",
    cancel: "Cancel",
    order_deleted: "Order deleted successfully",
    failed_to_delete_order: "Failed to delete order",
    vendor_blocked: "Vendor blocked successfully",
    vendor_unblocked: "Vendor unblocked successfully",
    failed_to_update: "Failed to update",
    loading: "Loading...",
    failed_to_fetch_orders: "Failed to fetch orders",
    search_vendors: "Search vendors...",
    select_category: "Select Category",
    sort_by: "Sort By",
    most_popular: "Most Popular",
    highest_rated: "Highest Rated",
    most_reviews: "Most Reviews",
    most_products: "Most Products",
    showing: "Showing",
    visit_shop: "Visit Shop",
    no_vendors_found: "No Vendors Found",
    try_different_search: "Try adjusting your search or filters",
    back_to_marketplace: "Back to Marketplace",
    // Vendor Shop
    contact_vendor: "Contact Vendor",
    send_message: "Send Message",
    member_since: "Member since",
    response_time: "Response time",
    about_vendor: "About This Vendor",
    description: "Description",
    location: "Location",
    contact_info: "Contact Information",
    search_products: "Search products...",
    all_categories: "All",
    add_to_cart: "Add to Cart",
    out_of_stock: "Out of Stock",
    no_products_found: "No Products Found",
    rating_breakdown: "Rating Breakdown",
    stars: "stars",
    // Shop Configuration
    shop_settings: "Shop Settings",
    shop_configuration: "Shop Configuration",
    my_shop: "My Shop",
    manage_products: "Manage Products",
    shop_name: "Shop Name",
    shop_description: "Shop Description",
    shop_category: "Shop Category",
    shop_branding: "Shop Branding",
    shop_logo: "Shop Logo",
    shop_banner: "Shop Banner",
    shop_colors: "Shop Colors",
    primary_color: "Primary Color",
    save_changes: "Save Changes",
    changes_saved: "Changes saved successfully",
    product_name: "Product Name",
    product_description: "Product Description",
    product_price: "Product Price",
    product_category: "Product Category",
    product_image: "Product Image",
    in_stock: "In Stock",
    stock_quantity: "Stock Quantity",
    add_product: "Add Product",
    edit_product: "Edit Product",
    delete_product: "Delete Product",
    product_added: "Product added successfully",
    product_updated: "Product updated successfully",
    product_deleted: "Product deleted successfully",
    // Additional translations
    new_payment: "New Payment",
    general: "General",
    advanced: "Advanced",
    general_info: "General Information",
    general_info_desc: "Basic information about your shop",
    enter_shop_name: "Enter your shop name",
    enter_shop_desc: "Describe your shop and what you sell",
    characters: "characters",
    address: "Address",
    enter_address: "Enter your shop address",
    branding_desc: "Customize your shop's visual identity",
    upload_logo_text: "Click to upload or drag and drop your logo",
    upload_banner_text: "Click to upload or drag and drop your banner",
    or: "or",
    choose_file: "Choose File",
    color_desc: "This color will be used throughout your shop",
    preview: "Preview",
    advanced_settings: "Advanced Settings",
    advanced_settings_desc: "Configure additional shop options",
    public_shop: "Public Shop",
    public_shop_desc: "Make your shop visible in the marketplace",
    accept_online_orders: "Accept Online Orders",
    online_orders_desc: "Allow customers to place orders online",
    shipping_available: "Shipping Available",
    shipping_desc: "Offer shipping to customers",
    min_order_amount: "Minimum Order Amount",
    min_order_desc: "Set a minimum amount for orders (0 for no minimum)",
    manage_products_desc: "Add and manage your product catalog",
    enter_product_name: "Enter product name",
    enter_product_desc: "Describe your product",
    enter_image_url: "Enter image URL",
    in_stock_desc: "Product is available for purchase",
    add_product_desc: "Add a new product to your catalog",
    edit_product_desc: "Update product information",
    upload_image_text: "Click to upload or drag and drop product image",
    total_products: "Total Products",
    stock: "Stock",
    units: "units",
    edit: "Edit",
    delete: "Delete",
    add_first_product: "Add your first product to get started",
    delete_product_confirm: "Are you sure you want to delete",
    action_cannot_undone: "This action cannot be undone.",
    // Cart & Checkout
    shopping_cart: "Shopping Cart",
    cart_empty: "Your cart is empty",
    cart_empty_desc: "Start adding items to your cart",
    item: "item",
    items: "items",
    in_cart: "in your cart",
    remove: "Remove",
    order_summary: "Order Summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    calculated_checkout: "Calculated at checkout",
    total: "Total",
    proceed_checkout: "Proceed to Checkout",
    continue_shopping: "Continue Shopping",
    checkout: "Checkout",
    checkout_desc: "Complete your order",
    contact_info_desc: "How can we contact you?",
    shipping_address: "Shipping Address",
    shipping_address_desc: "Where should we deliver your order?",
    city: "City",
    payment_method_desc: "Choose your preferred payment method",
    qty: "Qty",
    free: "Free",
    processing: "Processing",
    place_order: "Place Order",
    order_confirmed: "Order Confirmed!",
    order_confirmation_desc: "Thank you for your order",
    order_details: "Order Details",
    order_number: "Order Number",
    order_date: "Order Date",
    status: "Status",
    confirmed: "Confirmed",
    whats_next: "What's Next?",
    confirmation_email: "Order Confirmation Email",
    confirmation_email_desc: "We'll send you a confirmation email with order details",
    vendor_processing: "Vendor Processing",
    vendor_processing_desc: "The vendor will start preparing your order",
    delivery_updates: "Delivery Updates",
    delivery_updates_desc: "You'll receive notifications about your delivery status",
    need_help: "Need Help?",
    need_help_desc: "Our customer support team is here to assist you",
    contact_support: "Contact Support",
    call_us: "Call Us",
    track_order: "Track Order",
    order_placed_success: "Order placed successfully!",
    order_failed: "Order failed. Please try again.",
    added_to_cart: "Added to cart!",
    // Order Confirmation
    print_invoice: "Print Invoice",
    invoice: "Invoice",
    order_confirmed_title: "Thank you for your order!",
    order_confirmed_message: "Your order has been confirmed and is being prepared. A confirmation email has been sent to your email.",
    back_to_home: "Back to Home",
    customer_info: "Customer Information",
    name: "Name",
    shipping_info: "Shipping Information",
    home_delivery: "Home Delivery",
    unit_price: "Unit Price",
    quantity: "Quantity",
    order_processing_title: "Your order is being prepared",
    order_processing_desc: "Thank you for choosing FinMarket. Our team is actively working to prepare your order. You will receive an email with delivery details as soon as your package is shipped.",
    // Reviews
    anonymous: "Anonymous",
    post_anonymously: "Post anonymously (hide my name)",
    your_name: "Your Name",
    name_required: "Please enter your name",
    rating_required: "Please select a rating",
    review_submitted: "Review submitted successfully",
    rate_product: "Rate this product",
    share_experience: "Share your experience with",
    comment: "Comment (Optional)",
    write_review: "Write your review here...",
    submitting: "Submitting...",
    submit_review: "Submit Review",
    login_required_review: "Please login to leave a review",
    login_required_favorite: "Please login to add favorites",
  },
  fr: {
    // Common
    login: "Connexion",
    logout: "Déconnexion",
    register: "S'inscrire",
    dashboard: "Tableau de bord",
    transactions: "Transactions",
    settings: "Paramètres",
    profile: "Profil",
    marketplace: "Marché",
    products: "Produits",
    search: "Recherche",
    filters: "Filtres",
    verified: "Vérifié",
    reviews: "Avis",
    vendors: "Vendeurs",
    about: "À propos",
    features: "Fonctionnalités",
    // Dashboard
    total_revenue: "Revenu total",
    total_commissions: "Commissions totales",
    total_transactions: "Transactions totales",
    success_rate: "Taux de réussite",
    recent_transactions: "Transactions récentes",
    // Payment
    mobile_money: "Mobile Money",
    card_payment: "Paiement par carte",
    payment_success: "Paiement réussi",
    payment_failed: "Paiement échoué",
    // Onboarding
    business_info: "Informations commerciales",
    owner_info: "Informations du propriétaire",
    kyc_documents: "Documents KYC",
    bank_details: "Coordonnées bancaires",
    review_submit: "Vérifier et soumettre",
    // Forms
    email: "Email",
    password: "Mot de passe",
    first_name: "Prénom",
    last_name: "Nom",
    phone: "Numéro de téléphone",
    submit: "Soumettre",
    cancel: "Annuler",
    continue: "Continuer",
    back: "Retour",
    // Landing Page
    hero_title: "Votre Business en Ligne, Simplifié",
    hero_subtitle: "Créez votre boutique, gérez vos commandes et suivez vos revenus en temps réel. Une plateforme intuitive pour vendeurs ambitieux et acheteurs exigeants.",
    start_selling: "Commencez à vendre aujourd'hui",
    browse_marketplace: "Parcourir le marché",
    get_started: "Commencer",
    become_vendor: "Devenez vendeur",
    stat_vendors: "Vendeurs actifs",
    stat_transactions: "Transactions",
    stat_satisfaction: "Taux de satisfaction",
    stat_support: "Support client",
    features_title: "Tout ce dont vous avez besoin pour réussir",
    features_subtitle: "Fonctionnalités puissantes conçues pour les commerçants africains",
    feature_marketplace: "Tableau de Bord Vendeur",
    feature_marketplace_desc: "Suivez vos performances, ventes et produits avec un tableau de bord interactif.",
    feature_payments: "Gestion de Commandes",
    feature_payments_desc: "Gérez vos commandes de la réception à la livraison avec des mises à jour en temps réel.",
    feature_secure: "Sécurité & Conformité",
    feature_secure_desc: "Processus KYC intégré pour garantir des vendeurs vérifiés et des transactions sécurisées.",
    feature_analytics: "Analyse en temps réel",
    feature_analytics_desc: "Suivez les ventes, le revenu et les insights clients en temps réel",
    feature_multilang: "Support multilingue",
    feature_multilang_desc: "Servez les clients en anglais et français",
    feature_fast: "Rapide & Fiable",
    feature_fast_desc: "Plateforme ultra-rapide avec une garantie de disponibilité de 99,9%",
    how_it_works: "Comment ça fonctionne",
    how_it_works_subtitle: "Commencez en trois étapes simples",
    step_register: "Inscription & Vérification",
    step_register_desc: "Créez votre compte et complétez le processus KYC pour devenir un vendeur vérifié",
    step_setup: "Remplissez votre Boutique",
    step_setup_desc: "Ajoutez des produits, gérez les stocks et fixez vos prix facilement",
    step_sell: "Vendez & Encaissez",
    step_sell_desc: "Recevez des commandes, gérez les expéditions et suivez vos gains",
    benefits_title: "Pourquoi choisir FinMarket",
    benefits_subtitle: "Rejoignez des milliers de commerçants réussis",
    benefit_commission: "Taux de commission transparents",
    benefit_dashboard: "Tableau de bord analytique en temps réel",
    benefit_mobile: "Conception axée sur les mobiles - gérez votre boutique à la volée",
    benefit_support: "Support client 24/7 en plusieurs langues",
    benefit_kyc: "Vérification KYC rapide",
    benefit_international: "Acceptez les paiements internationaux",
    cta_title: "Prêt à commencer à vendre ?",
    cta_subtitle: "Rejoignez notre marché aujourd'hui et faites grandir votre entreprise",
    create_account: "Créez votre compte",
    footer_desc: "Plateforme de marché financier meneuse en Afrique",
    footer_product: "Produit",
    footer_company: "Entreprise",
    footer_legal: "Légal",
    pricing: "Tarification",
    about_us: "À propos de nous",
    contact: "Contact",
    careers: "Postes vacants",
    privacy_policy: "Politique de confidentialité",
    terms_service: "Conditions d'utilisation",
    cookies: "Cookies",
    all_rights_reserved: "Tous droits réservés",
    // About Page
    about_title: "À propos de FinMarket",
    about_subtitle: "Autonomiser le commerce africain grâce à la technologie",
    about_content: "FinMarket est une plateforme de marché numérique leader conçue pour connecter les commerçants et les clients à travers l'Afrique. Notre mission est d'offrir des opportunités économiques égales en construisant une plateforme fiable, sécurisée et facile à utiliser pour l'achat et la vente de biens et services.",
    // Contact Page
    contact_title: "Contactez-nous",
    contact_subtitle: "Nous sommes là pour vous aider",
    contact_address: "123 Quartier des Affaires, Cotonou, Bénin",
    contact_email: "support@finmarket.com",
    contact_phone: "+229 01 23 45 67",
    send_message_btn: "Envoyer le message",
    message_sent: "Message envoyé ! Nous vous répondrons bientôt.",
    // Privacy & Terms
    privacy_title: "Politique de confidentialité",
    privacy_intro: "Chez FinMarket, nous prenons votre vie privée au sérieux. Cette politique décrit comment nous collectons et utilisons vos données.",
    terms_title: "Conditions d'utilisation",
    terms_intro: "En utilisant FinMarket, vous acceptez ces conditions. Veuillez les lire attentivement.",
    last_updated: "Dernière mise à jour : Février 2026",
    privacy_section1_title: "1. Collecte de données",
    privacy_section1_text: "Nous collectons les informations que vous nous fournissez directement, par exemple lorsque vous créez ou modifiez votre compte, demandez des services à la demande, contactez le support client ou communiquez avec nous.",
    privacy_section2_title: "2. Utilisation des informations",
    privacy_section2_text: "Nous utilisons les informations que nous collectons pour fournir, maintenir et améliorer nos services, comme faciliter les paiements, envoyer des reçus, fournir les produits et services demandés, développer de nouvelles fonctionnalités et assurer le support client.",
    privacy_section3_title: "3. Sécurité des données",
    privacy_section3_text: "Nous mettons en œuvre des mesures techniques et organisationnelles appropriées pour protéger vos données personnelles contre l'accès, l'utilisation, la divulgation, l'altération ou la destruction non autorisés.",
    terms_section1_title: "1. Acceptation des conditions",
    terms_section1_text: "En accédant ou en utilisant nos services, vous acceptez d'être lié par ces conditions. Si vous n'acceptez pas ces conditions, vous ne pouvez pas accéder ou utiliser les services.",
    terms_section2_title: "2. Obligations des vendeurs",
    terms_section2_text: "Les vendeurs doivent fournir des informations exactes sur leurs produits et services. Ils sont responsables de l'exécution des commandes et de la satisfaction des clients.",
    terms_section3_title: "3. Obligations des utilisateurs",
    terms_section3_text: "Les utilisateurs certifient avoir au moins 18 ans. Ils sont responsables du maintien de la confidentialité de leurs identifiants de compte.",
    terms_section4_title: "4. Paiements",
    terms_section4_text: "Tous les paiements sont traités de manière sécurisée. FinMarket n'est pas responsable des problèmes découlant des processeurs de paiement tiers.",
    message_label: "Message",

    about_section2_content: "Nous croyons au pouvoir de la technologie pour transformer des vies. En connectant les vendeurs et les acheteurs, nous créons de la valeur pour tout l'écosystème. Notre plateforme est fondée sur la confiance, la transparence et l'efficacité.",
    // Marketplace
    marketplace_title: "Découvrez des vendeurs exceptionnels",
    marketplace_subtitle: "Parcourez des centaines de vendeurs vérifiés et trouvez exactement ce dont vous avez besoin",
    // Admin Orders
    orders_management: "Gestion des commandes",
    manage_all_orders: "Gérer toutes les commandes",
    total_revenue: "Chiffre d'affaires total",
    platform_commission: "Commission plateforme",
    commission_rate: "Taux de commission",
    all_vendors: "Tous les vendeurs",
    vendor: "Vendeur",
    search_orders: "Rechercher des commandes",
    // Admin Drivers
    drivers_management: "Gestion des Livreurs",
    manage_drivers_subtitle: "Liste des livreurs partenaires et contact direct",
    drivers_list: "Liste des Livreurs",
    search_driver: "Rechercher un livreur...",
    driver_name: "Nom",
    zone: "Zone",
    orders_completed: "Courses",
    add_driver: "Ajouter un livreur",
    edit_driver: "Modifier un livreur",
    delete_driver: "Supprimer un livreur",
    delete_driver_confirm: "Êtes-vous sûr de vouloir supprimer ce livreur ? Cette action est irréversible.",
    driver_added: "Livreur ajouté avec succès",
    driver_updated: "Livreur mis à jour avec succès",
    driver_deleted: "Livreur supprimé avec succès",
    no_drivers_found: "Aucun livreur trouvé",
    available: "Disponible",
    busy: "En course",
    offline: "Hors ligne",
    name: "Nom",
    save: "Enregistrer",
    vendor_drivers_subtitle: "Contactez un livreur pour vos expéditions",
    filters: "Filtres",
    start_date: "Date de début",
    end_date: "Date de fin",
    status: "Statut",
    all_statuses: "Tous les statuts",
    clear: "Effacer",
    orders: "Commandes",
    newest_first: "Plus récents",
    oldest_first: "Plus anciens",
    no_orders_found: "Aucune commande trouvée",
    order_number: "Numéro de commande",
    date: "Date",
    customer: "Client",
    amount: "Montant",
    actions: "Actions",
    confirm_delete: "Confirmer la suppression",
    delete_order_warning: "Êtes-vous sûr de vouloir supprimer cette commande ? Cette action est irréversible.",
    delete: "Supprimer",
    cancel: "Annuler",
    order_deleted: "Commande supprimée avec succès",
    failed_to_delete_order: "Échec de la suppression de la commande",
    vendor_blocked: "Vendeur bloqué avec succès",
    vendor_unblocked: "Vendeur débloqué avec succès",
    failed_to_update: "Échec de la mise à jour",
    loading: "Chargement...",
    failed_to_fetch_orders: "Échec du chargement des commandes",
    marketplace_subtitle: "Parcourez des centaines de vendeurs vérifiés et trouvez exactement ce dont vous avez besoin",
    search_vendors: "Recherchez des vendeurs...",
    select_category: "Sélectionnez une catégorie",
    sort_by: "Trier par",
    most_popular: "Le plus populaire",
    highest_rated: "Le mieux noté",
    most_reviews: "Le plus revu",
    most_products: "Le plus de produits",
    showing: "Affichage",
    visit_shop: "Visiter la boutique",
    no_vendors_found: "Aucun vendeur trouvé",
    try_different_search: "Essayez d'ajuster votre recherche ou vos filtres",
    back_to_marketplace: "Retour au marché",
    // Vendor Shop
    contact_vendor: "Contacter le vendeur",
    send_message: "Envoyer un message",
    member_since: "Membre depuis",
    response_time: "Temps de réponse",
    about_vendor: "À propos de ce vendeur",
    description: "Description",
    location: "Localisation",
    contact_info: "Informations de contact",
    search_products: "Recherchez des produits...",
    all_categories: "Tous",
    add_to_cart: "Ajouter au panier",
    out_of_stock: "En rupture de stock",
    no_products_found: "Aucun produit trouvé",
    rating_breakdown: "Répartition des notes",
    stars: "étoiles",
    // Shop Configuration
    shop_settings: "Paramètres de la boutique",
    shop_configuration: "Configuration de la boutique",
    my_shop: "Ma boutique",
    manage_products: "Gérer les produits",
    shop_name: "Nom de la boutique",
    shop_description: "Description de la boutique",
    shop_category: "Catégorie de la boutique",
    shop_branding: "Branding de la boutique",
    shop_logo: "Logo de la boutique",
    shop_banner: "Bannière de la boutique",
    shop_colors: "Couleurs de la boutique",
    primary_color: "Couleur principale",
    save_changes: "Enregistrer les modifications",
    changes_saved: "Modifications enregistrées avec succès",
    product_name: "Nom du produit",
    product_description: "Description du produit",
    product_price: "Prix du produit",
    product_category: "Catégorie du produit",
    product_image: "Image du produit",
    in_stock: "En stock",
    stock_quantity: "Quantité en stock",
    add_product: "Ajouter un produit",
    edit_product: "Modifier un produit",
    delete_product: "Supprimer un produit",
    product_added: "Produit ajouté avec succès",
    product_updated: "Produit mis à jour avec succès",
    product_deleted: "Produit supprimé avec succès",
    // Additional translations
    new_payment: "Nouveau paiement",
    general: "Général",
    advanced: "Avancé",
    general_info: "Informations générales",
    general_info_desc: "Informations de base sur votre boutique",
    enter_shop_name: "Entrez le nom de votre boutique",
    enter_shop_desc: "Décrivez votre boutique et ce que vous vendez",
    characters: "caractères",
    address: "Adresse",
    enter_address: "Entrez l'adresse de votre boutique",
    branding_desc: "Personnalisez l'identité visuelle de votre boutique",
    upload_logo_text: "Cliquez pour télécharger ou glissez-déposez votre logo",
    upload_banner_text: "Cliquez pour télécharger ou glissez-déposez votre bannière",
    or: "ou",
    choose_file: "Choisir un fichier",
    color_desc: "Cette couleur sera utilisée dans toute votre boutique",
    preview: "Aperçu",
    advanced_settings: "Paramètres avancés",
    advanced_settings_desc: "Configurez les options supplémentaires de la boutique",
    public_shop: "Boutique publique",
    public_shop_desc: "Rendre votre boutique visible sur le marché",
    accept_online_orders: "Accepter les commandes en ligne",
    online_orders_desc: "Permettre aux clients de passer des commandes en ligne",
    shipping_available: "Livraison disponible",
    shipping_desc: "Offrir la livraison aux clients",
    min_order_amount: "Montant minimum de commande",
    min_order_desc: "Définir un montant minimum pour les commandes (0 pour aucun minimum)",
    manage_products_desc: "Ajouter et gérer votre catalogue de produits",
    enter_product_name: "Entrez le nom du produit",
    enter_product_desc: "Décrivez votre produit",
    enter_image_url: "Entrez l'URL de l'image",
    in_stock_desc: "Le produit est disponible à l'achat",
    add_product_desc: "Ajouter un nouveau produit à votre catalogue",
    edit_product_desc: "Mettre à jour les informations du produit",
    upload_image_text: "Cliquez pour télécharger ou glissez-déposez l'image du produit",
    total_products: "Total des produits",
    stock: "Stock",
    units: "unités",
    edit: "Modifier",
    delete: "Supprimer",
    add_first_product: "Ajoutez votre premier produit pour commencer",
    delete_product_confirm: "Êtes-vous sûr de vouloir supprimer",
    action_cannot_undone: "Cette action ne peut pas être annulée.",
    // Cart & Checkout
    shopping_cart: "Panier",
    cart_empty: "Votre panier est vide",
    cart_empty_desc: "Commencez à ajouter des articles à votre panier",
    item: "article",
    items: "articles",
    in_cart: "dans votre panier",
    remove: "Retirer",
    order_summary: "Résumé de la commande",
    subtotal: "Sous-total",
    shipping: "Livraison",
    calculated_checkout: "Calculé à la caisse",
    total: "Total",
    proceed_checkout: "Passer à la caisse",
    continue_shopping: "Continuer les achats",
    checkout: "Caisse",
    checkout_desc: "Complétez votre commande",
    contact_info_desc: "Comment pouvons-nous vous contacter ?",
    shipping_address: "Adresse de livraison",
    shipping_address_desc: "Où devons-nous livrer votre commande ?",
    city: "Ville",
    payment_method_desc: "Choisissez votre méthode de paiement préférée",
    qty: "Qté",
    free: "Gratuit",
    processing: "Traitement",
    place_order: "Passer la commande",
    order_confirmed: "Commande confirmée !",
    order_confirmation_desc: "Merci pour votre commande",
    order_details: "Détails de la commande",
    order_number: "Numéro de commande",
    order_date: "Date de commande",
    status: "Statut",
    confirmed: "Confirmé",
    whats_next: "Et maintenant ?",
    confirmation_email: "Email de confirmation de commande",
    confirmation_email_desc: "Nous vous enverrons un email de confirmation avec les détails de la commande",
    vendor_processing: "Traitement par le vendeur",
    vendor_processing_desc: "Le vendeur commencera à préparer votre commande",
    delivery_updates: "Mises à jour de livraison",
    delivery_updates_desc: "Vous recevrez des notifications sur l'état de votre livraison",
    need_help: "Besoin d'aide ?",
    need_help_desc: "Notre équipe de support client est là pour vous aider",
    contact_support: "Contacter le support",
    call_us: "Appelez-nous",
    track_order: "Suivre la commande",
    order_placed_success: "Commande passée avec succès !",
    order_failed: "Échec de la commande. Veuillez réessayer.",
    added_to_cart: "Ajouté au panier !",
    // Order Confirmation
    print_invoice: "Imprimer le Bon de commande",
    invoice: "Bon de commande",
    order_confirmed_title: "Merci pour votre commande !",
    order_confirmed_message: "Votre commande a été confirmée et est en cours de préparation. Un email de confirmation a été envoyé à votre adresse.",
    back_to_home: "Retour à l'accueil",
    customer_info: "Informations client",
    shipping_info: "Informations de livraison",
    home_delivery: "Livraison à domicile",
    unit_price: "Prix unitaire",
    quantity: "Quantité",
    order_processing_title: "Votre commande est en cours de préparation",
    order_processing_desc: "Nous vous remercions d'avoir choisi FinMarket. Notre équipe travaille activement à préparer votre commande. Vous recevrez un email avec les détails de livraison dès que votre colis sera expédié.",
    // Reviews
    anonymous: "Anonyme",
    post_anonymously: "Publier de façon anonyme (masquer mon nom)",
    your_name: "Votre nom",
    name_required: "Veuillez entrer votre nom",
    rating_required: "Veuillez sélectionner une note",
    review_submitted: "Avis soumis avec succès",
    rate_product: "Noter ce produit",
    share_experience: "Partagez votre expérience avec",
    comment: "Commentaire (Optionnel)",
    write_review: "Écrivez votre avis ici...",
    submitting: "Envoi en cours...",
    submit_review: "Soumettre l'avis",
    login_required_review: "Veuillez vous connecter pour laisser un avis",
    login_required_favorite: "Veuillez vous connecter pour ajouter aux favoris",
  },
};

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(() => {
    return "fr";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    // Force French translation
    return translations['fr']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}